var ListaVacia = [];
ListaVacia[0] = 'Ninguno';

var ListaSiNo = [];
ListaSiNo[0] = 'No';
ListaSiNo[1] = 'Si';

var ListaHoVe = [];
ListaHoVe[0] = 'Horizontal';
ListaHoVe[1] = 'Vertical';

var ListaOnOffAuto = [];
ListaOnOffAuto[0] = 'Apagado';
ListaOnOffAuto[1] = 'Encendido';
ListaOnOffAuto[2] = 'Automático';

var TipoHW = [];
TipoHW[0] = 'Ninguno';
TipoHW[1] = 'WiFi I/O';
TipoHW[2] = 'RBPi';
TipoHW[3] = 'DSC';
TipoHW[4] = 'Garnet';
TipoHW[5] = 'Touch';

var EstadoHW = [];
EstadoHW[0] = '<img src="images/no.png">';
EstadoHW[1] = '<img src="images/ok.png">';

var TipoAss = [];
TipoAss[0] = 'Salida';
TipoAss[1] = 'Entrada';
TipoAss[2] = 'Entrada Analogica';
TipoAss[3] = 'Salida Alarma';
TipoAss[4] = 'Entrada Alarma';
TipoAss[5] = 'Salida Pulso';
TipoAss[6] = 'Periferico';

var PortAss = [];
PortAss[0] =  { value: 'IO1',  		label: 'IO1' }
PortAss[1] =  { value: 'IO2',  		label: 'IO2' }
PortAss[2] =  { value: 'IO3',  		label: 'IO3' }
PortAss[3] =  { value: 'IO4',  		label: 'IO4' }
PortAss[4] =  { value: 'IO5',  		label: 'IO5' }
PortAss[5] =  { value: 'IO6',  		label: 'IO6' }
PortAss[6] =  { value: 'IO7',  		label: 'IO7' }
PortAss[7] =  { value: 'IO8',  		label: 'IO8' }
PortAss[8] =  { value: 'OUT1', 		label: 'OUT1' }
PortAss[9] =  { value: 'OUT2', 		label: 'OUT2' }
PortAss[10] = { value: 'OUT3', 		label: 'OUT3' }
PortAss[11] = { value: 'OUT4', 		label: 'OUT4' }
PortAss[12] = { value: 'OUT5', 		label: 'OUT5' }
PortAss[13] = { value: 'OUT6', 		label: 'OUT6' }
PortAss[14] = { value: 'OUT7', 		label: 'OUT7' }
PortAss[15] = { value: 'OUT8', 		label: 'OUT8' }
PortAss[16] = { value: 'TEMP', 		label: 'Sensor Temperatura' }
PortAss[17] = { value: 'HUM', 		label: 'Sensor Humedad' }
PortAss[18] = { value: 'CARD', 		label: 'Lector Tarjetas' }

var GrupoVisual = [];
GrupoVisual[0] = 'Ninguno';
GrupoVisual[1] = 'Alarma';
GrupoVisual[2] = 'Iluminación';
GrupoVisual[3] = 'Puertas';
GrupoVisual[4] = 'Climatización';
GrupoVisual[5] = 'Cámaras';
GrupoVisual[6] = 'Riego';

var TablaAcciones = [];
TablaAcciones[0] = 'Ninguno';
TablaAcciones[1] = 'Encender';
TablaAcciones[2] = 'Apagar';
TablaAcciones[3] = 'Cambiar';
TablaAcciones[4] = 'Pulso';

var TipoAuto = [];
TipoAuto[0] = 'Ninguno';
TipoAuto[1] = 'Riego';
TipoAuto[2] = 'Calefaccion';
TipoAuto[3] = 'Aire Acondicionado';
TipoAuto[4] = 'Foto Celula';
TipoAuto[5] = 'Caldera';
TipoAuto[6] = 'Pileta';

var TipoZonaAlarma = [];
TipoZonaAlarma[0] = 'Normal';
TipoZonaAlarma[1] = 'Demorada';
TipoZonaAlarma[2] = 'Incendio';
TipoZonaAlarma[3] = 'Panico';
TipoZonaAlarma[4] = 'Emergencia Médica'

var TipoActivacionAlarma = [];
TipoActivacionAlarma[0] = 'No';
TipoActivacionAlarma[1] = 'Parcial';
TipoActivacionAlarma[2] = 'Total';

var TipoSalidaAlarma = [];
TipoSalidaAlarma[0] = 'Sirena';
TipoSalidaAlarma[1] = 'Buzer';
TipoSalidaAlarma[2] = 'Testigo';

var TablaMeses = [];
TablaMeses[0] = 'Todos';
TablaMeses[1] = 'Enero';
TablaMeses[2] = 'Febrero';
TablaMeses[3] = 'Marzo';
TablaMeses[4] = 'Abril';
TablaMeses[5] = 'Mayo';
TablaMeses[6] = 'Junio';
TablaMeses[7] = 'Julio';
TablaMeses[8] = 'Agosto';
TablaMeses[9] = 'Septiembre';
TablaMeses[10] = 'Octubre';
TablaMeses[11] = 'Noviembre';
TablaMeses[12] = 'Diciembre';

var TablaDias = [];
TablaDias[0] = 'Todos';
TablaDias[1] = '1';
TablaDias[2] = '2';
TablaDias[3] = '3';
TablaDias[4] = '4';
TablaDias[5] = '5';
TablaDias[6] = '6';
TablaDias[7] = '7';
TablaDias[8] = '8';
TablaDias[9] = '9';
TablaDias[10] = '10';
TablaDias[11] = '11';
TablaDias[12] = '12';
TablaDias[13] = '13';
TablaDias[14] = '14';
TablaDias[15] = '15';
TablaDias[16] = '16';
TablaDias[17] = '17';
TablaDias[18] = '18';
TablaDias[19] = '19';
TablaDias[20] = '20';
TablaDias[21] = '21';
TablaDias[22] = '22';
TablaDias[23] = '23';
TablaDias[24] = '24';
TablaDias[25] = '25';
TablaDias[26] = '26';
TablaDias[27] = '27';
TablaDias[28] = '28';
TablaDias[29] = '29';
TablaDias[30] = '30';
TablaDias[31] = '31';

var TablaHoras = [];
TablaHoras[0] = '0';
TablaHoras[1] = '1';
TablaHoras[2] = '2';
TablaHoras[3] = '3';
TablaHoras[4] = '4';
TablaHoras[5] = '5';
TablaHoras[6] = '6';
TablaHoras[7] = '7';
TablaHoras[8] = '8';
TablaHoras[9] = '9';
TablaHoras[10] = '10';
TablaHoras[11] = '11';
TablaHoras[12] = '12';
TablaHoras[13] = '13';
TablaHoras[14] = '14';
TablaHoras[15] = '15';
TablaHoras[16] = '16';
TablaHoras[17] = '17';
TablaHoras[18] = '18';
TablaHoras[19] = '19';
TablaHoras[20] = '20';
TablaHoras[21] = '21';
TablaHoras[22] = '22';
TablaHoras[23] = '23';
TablaHoras[24] = 'Todas';

var TablaMinutos = [];
TablaMinutos[0] = '00';
TablaMinutos[1] = '01';
TablaMinutos[2] = '02';
TablaMinutos[3] = '03';
TablaMinutos[4] = '04';
TablaMinutos[5] = '05';
TablaMinutos[6] = '06';
TablaMinutos[7] = '07';
TablaMinutos[8] = '08';
TablaMinutos[9] = '09';
TablaMinutos[10] = '10';
TablaMinutos[11] = '11';
TablaMinutos[12] = '12';
TablaMinutos[13] = '13';
TablaMinutos[14] = '14';
TablaMinutos[15] = '15';
TablaMinutos[16] = '16';
TablaMinutos[17] = '17';
TablaMinutos[18] = '18';
TablaMinutos[19] = '19';
TablaMinutos[20] = '20';
TablaMinutos[21] = '21';
TablaMinutos[22] = '22';
TablaMinutos[23] = '23';
TablaMinutos[24] = '24';
TablaMinutos[25] = '25';
TablaMinutos[26] = '26';
TablaMinutos[27] = '27';
TablaMinutos[28] = '28';
TablaMinutos[29] = '29';
TablaMinutos[30] = '30';
TablaMinutos[31] = '31';
TablaMinutos[32] = '32';
TablaMinutos[33] = '33';
TablaMinutos[34] = '34';
TablaMinutos[35] = '35';
TablaMinutos[36] = '36';
TablaMinutos[37] = '37';
TablaMinutos[38] = '38';
TablaMinutos[39] = '39';
TablaMinutos[40] = '40';
TablaMinutos[41] = '41';
TablaMinutos[42] = '42';
TablaMinutos[43] = '43';
TablaMinutos[44] = '44';
TablaMinutos[45] = '45';
TablaMinutos[46] = '46';
TablaMinutos[47] = '47';
TablaMinutos[48] = '48';
TablaMinutos[49] = '49';
TablaMinutos[50] = '50';
TablaMinutos[51] = '51';
TablaMinutos[52] = '52';
TablaMinutos[53] = '53';
TablaMinutos[54] = '54';
TablaMinutos[55] = '55';
TablaMinutos[56] = '56';
TablaMinutos[57] = '57';
TablaMinutos[58] = '58';
TablaMinutos[59] = '59';
TablaMinutos[60] = '60';

var ImagenObjeto = [];
ImagenObjeto[0] = { value: 'key.png', label: 'Llave' }
ImagenObjeto[1] = { value: 'lamp1.png', label: 'Luz encendida' }
ImagenObjeto[2] = { value: 'lamp0.png', label: 'Luz apagada' }
ImagenObjeto[3] = { value: 'calef1.png', label: 'Estufa encendida' }
ImagenObjeto[4] = { value: 'calef0.png', label: 'Estufa apagada' }
ImagenObjeto[5] = { value: 'vent1.png', label: 'Extractor encendido' }
ImagenObjeto[6] = { value: 'vent0.png', label: 'Extractor apagado' }
ImagenObjeto[7] = { value: 'aire1.png', label: 'Aire encendido' }
ImagenObjeto[8] = { value: 'aire0.png', label: 'Aire apagado' }
ImagenObjeto[9] = { value: 'campana1.png', label: 'Campanilla encendida' }
ImagenObjeto[10] = { value: 'campana0.png', label: 'Campanilla apagada' }
ImagenObjeto[11] = { value: 'lock1.png', label: 'Candado cerrado' }
ImagenObjeto[12] = { value: 'lock0.png', label: 'Candado abierto' }
ImagenObjeto[13] = { value: 'manguera1.png', label: 'Riego encendido' }
ImagenObjeto[14] = { value: 'manguera0.png', label: 'Riego apagado' }
ImagenObjeto[15] = { value: 'pir1.png', label: 'PIR encendido' }
ImagenObjeto[16] = { value: 'pir0.png', label: 'PIR apagado' }
ImagenObjeto[17] = { value: 'sirena1.png', label: 'Sirena encendida' }
ImagenObjeto[18] = { value: 'sirena0.png', label: 'Sirena apagada' }
ImagenObjeto[19] = { value: 'switch1.png', label: 'Switch encendido' }
ImagenObjeto[20] = { value: 'switch0.png', label: 'Switch apagado' }
ImagenObjeto[21] = { value: 'door1.png', label: 'Puerta abierta' }
ImagenObjeto[22] = { value: 'door0.png', label: 'Puerta cerrada' }
ImagenObjeto[23] = { value: 'window1.png', label: 'Ventana abierta' }
ImagenObjeto[24] = { value: 'window0.png', label: 'Ventana cerrada' }

var ListaEventoTouch = [];
ListaEventoTouch[0] = 'Nada';
ListaEventoTouch[1] = 'On';
ListaEventoTouch[2] = 'Off';
ListaEventoTouch[3] = 'Switch';
ListaEventoTouch[4] = 'Pulso';
ListaEventoTouch[5] = '';
ListaEventoTouch[6] = '';
ListaEventoTouch[7] = '';
ListaEventoTouch[8] = '';
ListaEventoTouch[9] = '9';
ListaEventoTouch[10] = 'Config';
ListaEventoTouch[11] = 'Home';
ListaEventoTouch[12] = 'Prev';
ListaEventoTouch[13] = 'Next'
