#!/bin/sh

sudo cp -uva *.html /var/lib/microdom/html/
sudo cp -uva images/* /var/lib/microdom/html/images/
sudo cp -uva css/* /var/lib/microdom/html/css/
sudo cp -uva js/* /var/lib/microdom/html/js/
sudo cp -uva data/* /var/lib/microdom/html/data/

